import { BrowserRouter, Link, Navigate, Route, Routes } from 'react-router-dom';
import { AppLayout } from './layouts/AppLayout';
import { useCamera } from './hooks/useCamera';
import { useRef, useState } from 'react';

function Landing(){return <section className="hero"><div className="eyebrow">● SYSTEM ONLINE · VISION ENGINE READY</div><h1>NEXA<br/><em>VISION AI</em></h1><p className="tagline">SEE MORE.<br/>UNDERSTAND MORE.</p><p>Advanced AI-powered computer vision for the next generation.</p><div className="actions"><Link className="btn primary" to="/app/vision">OPEN VISION</Link><Link className="btn" to="/app">EXPLORE SYSTEM</Link></div><div className="lens"><div className="scan-ring"/><span>OPTICAL CORE // SYS-01</span></div></section>}
function Login(){return <section className="center-page"><div className="login-card"><div className="brand"><span>NEXA</span><small>VISION AI</small></div><h2>WELCOME TO THE VISION SYSTEM</h2><p>Secure access to your AI vision workspace.</p><a className="btn primary wide" href={`${import.meta.env.VITE_API_URL ?? 'http://localhost:3000'}/api/auth/google`}>CONTINUE WITH GOOGLE</a></div></section>}
function Dashboard(){return <div><div className="page-head"><div><div className="eyebrow">WELCOME BACK</div><h2>Vision workspace</h2><p>AI perception systems ready for your next scan.</p></div><div className="status"><i/> SYSTEM ONLINE</div></div><div className="metric-grid">{[['TOTAL ANALYSES','0'],['VISION SCANS','0'],['LAST ANALYSIS','—'],['SYSTEM STATUS','READY']].map(([a,b])=><div className="metric" key={a}><span>{a}</span><strong>{b}</strong></div>)}</div><div className="core"><div><div className="eyebrow">NEXA // VISION CORE</div><h3>See the world through an AI lens.</h3><p>Open the camera, capture an image, then send it through the server-side vision engine.</p><Link className="btn primary" to="/app/vision">START VISION SCAN</Link></div><div className="core-visual"><div className="core-grid"/><div className="core-ring"/></div></div></div>}
function Vision(){const {videoRef,active,error,capture}=useCamera(); const fileRef=useRef<HTMLInputElement>(null); const [img,setImg]=useState<string|null>(null); const [state,setState]=useState('CAMERA READY'); const [result,setResult]=useState<string|null>(null); const [busy,setBusy]=useState(false); const snap=()=>{const data=capture(); if(data){setImg(data);setState('IMAGE READY');}}; const upload=(f:File)=>{if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>10*1024*1024){setState('VISION ENGINE ERROR');return;}const u=URL.createObjectURL(f);setImg(u);setState('IMAGE READY');}; const analyze=async()=>{if(!img)return;setBusy(true);setState('ANALYZING...');await new Promise(r=>setTimeout(r,800));setResult('AI analysis endpoint is ready. Configure GEMINI_API_KEY and authentication on the server to receive live results.');setState('ANALYSIS COMPLETE');setBusy(false);}; return <div><div className="page-head"><div><div className="eyebrow">AI VISION</div><h2>Vision Camera</h2><p>OPTICAL ENGINE · <span className="live">{active?'ACTIVE':'READY'}</span></p></div><div className="status"><i/> {state}</div></div><div className="vision-grid"><div className="camera-card"><video ref={videoRef} playsInline muted className={img?'hidden':''}/>{img&&<img src={img} alt="Captured vision frame"/>}<div className="hud"><span>AI VISION</span><span>SCANNING AREA</span><b>VISION ENGINE<br/>{active?'READY':'WAITING'}</b></div><div className="corner c1"/><div className="corner c2"/><div className="corner c3"/><div className="corner c4"/></div><div className="controls"><button className="shutter" onClick={snap} aria-label="Capture image">●</button><button className="btn" onClick={()=>fileRef.current?.click()}>UPLOAD IMAGE</button><input ref={fileRef} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f)upload(f)}}/><button className="btn primary" disabled={!img||busy} onClick={()=>void analyze()}>{busy?'SCANNING...':'ANALYZE'}</button>{error&&<p className="error">{error}</p>}</div>{result&&<div className="result-card"><div className="eyebrow">VISION ANALYSIS COMPLETE</div><h3>AI INSIGHT</h3><p>{result}</p><div className="result-pills"><span>DESCRIPTION</span><span>OBJECTS DETECTED</span><span>ENVIRONMENT</span><span>CONFIDENCE · HIGH</span></div></div>}</div></div>}
function SimplePage({title,sub}:{title:string;sub:string}){return <div className="simple"><div className="eyebrow">NEXA // SYSTEM</div><h2>{title}</h2><p>{sub}</p><div className="empty-card">MODULE READY<span>Connect the backend and database to populate live data.</span></div></div>}
export default function App(){return <BrowserRouter><Routes><Route path="/" element={<Landing/>}/><Route path="/login" element={<Login/>}/><Route path="/app" element={<AppLayout/>}><Route index element={<Dashboard/>}/><Route path="vision" element={<Vision/>}/><Route path="history" element={<SimplePage title="Vision History" sub="Your previous AI vision analyses."/>}/><Route path="profile" element={<SimplePage title="Profile" sub="Google account and system membership information."/>}/><Route path="settings" element={<SimplePage title="Settings" sub="Account, appearance, camera, system and security preferences."/>}/></Route><Route path="*" element={<Navigate to="/" replace/>}/></Routes></BrowserRouter>}
