import { BrowserRouter, Link, Navigate, Route, Routes } from 'react-router-dom';
import { AppLayout } from './layouts/AppLayout';
import { VisionCameraV2 } from './VisionCameraV2';

function Landing(){return <section className="hero"><div className="eyebrow">● SYSTEM ONLINE · VISION ENGINE READY</div><h1>NEXA<br/><em>VISION AI</em></h1><p className="tagline">SEE MORE.<br/>UNDERSTAND MORE.</p><p>Advanced AI-powered computer vision for the next generation.</p><div className="actions"><Link className="btn primary" to="/app/vision">OPEN VISION</Link><Link className="btn" to="/app">EXPLORE SYSTEM</Link></div></section>}
function Login(){return <section className="center-page"><div className="login-card"><div className="brand"><span>NEXA</span><small>VISION AI</small></div><h2>WELCOME TO THE VISION SYSTEM</h2><p>Secure access to your AI vision workspace.</p><a className="btn primary wide" href={`${import.meta.env.VITE_API_URL ?? 'http://localhost:3000'}/api/auth/google`}>CONTINUE WITH GOOGLE</a></div></section>}
function Dashboard(){return <div><div className="page-head"><div><div className="eyebrow">WELCOME BACK</div><h2>Vision workspace</h2><p>AI perception systems ready for your next scan.</p></div><div className="status"><i/> SYSTEM ONLINE</div></div><div className="core"><div><div className="eyebrow">NEXA // VISION CORE</div><h3>See the world through an AI lens.</h3><p>Camera capture, object detection and persistent camera settings.</p><Link className="btn primary" to="/app/vision">START VISION SCAN</Link></div></div></div>}
function Settings(){const get=(k:string,d:string)=>localStorage.getItem(k)||d; return <div className="settings-page"><div className="page-head"><div><div className="eyebrow">NEXA // CONTROL</div><h2>Camera Settings</h2><p>Settings are saved locally and survive page reloads.</p></div></div><div className="settings-card"><div className="setting-row"><strong>Camera</strong><span>{get('nexa-camera','environment')==='environment'?'Rear camera':'Front camera'}</span></div><div className="setting-row"><strong>Aspect ratio</strong><span>{get('nexa-ratio','16:9')}</span></div><div className="setting-row"><strong>Rotation</strong><span>{get('nexa-rotation','0')}°</span></div><p>Change these directly from the Vision Camera controls; the values remain stored on this device.</p></div></div>}
function Simple({title}:{title:string}){return <div className="simple"><div className="eyebrow">NEXA // SYSTEM</div><h2>{title}</h2><p>Module ready.</p></div>}
export default function AppFixed(){return <BrowserRouter><Routes><Route path="/" element={<Landing/>}/><Route path="/login" element={<Login/>}/><Route path="/app" element={<AppLayout/>}><Route index element={<Dashboard/>}/><Route path="vision" element={<VisionCameraV2/>}/><Route path="settings" element={<Settings/>}/><Route path="history" element={<Simple title="Vision History"/>}/><Route path="profile" element={<Simple title="Profile"/>}/></Route><Route path="*" element={<Navigate to="/" replace/>}/></Routes></BrowserRouter>}
